site_name: Terraform SuperSchema

theme:
  name: material

nav:
  - Why ?: "why.md"
  - How to use it:
    - "getting-started.md"
    - Resource doc example: "resource_example.md"
    - DataSource doc example: "datasource_example.md"
  - SuperSchema logic : "logic.md"
